### ISSUE TITLE
reset_camera = False, still does reset zoom

### ISSUE THREAD

**Issue by Jojain** [bernhard-42/jupyter-cadquery#52]
Hello,

I'm using the voilà viewer and while specifying `reset_camera = False` the zoom is reset to the defaults (the camera position works as intended though).

Is this a bug ? If yes, is there a workaround ?
Thanks !

**Comment by bernhard-42** [comment]
@Jojain Sorry for the late reply, I was away from any keyboard for the last 2 weeks.
Yes, this is a bug. Workaround is to write your adapted version of `show`, since `_convert` falsely sets `zoom` to the default value of `2.5`:

```python
from jupyter_cadquery.viewer.client import _convert, send

def show(*cad_objs, **kwargs):
    data = _convert(*cad_objs, **kwargs)
    if kwargs.get("zoom") is None:
        del data["config"]["zoom"]
    send(data)
```

The `if` clause is the only change to the original `show` command. I need to fix `_convert` in the next release.
